name: Get Plugin L-X release versions
description: Get release versions for the L-x releases from a specific Wordpress plugin like WooCommerce or Google Listing And Ads.

inputs:
  slug:
    description: The plugin slug to get the versions. (It should be a WordPress.org plugin)
    required: true
  releases:
    description: Number of releases to get. By default L-2 directive (3 releases)
    default: "3"
  includeRC:
    description: Whether to include Release Candidates in the fetched versions. (WordPress is Not compatible with this)
    default: "false"
  includePatches:
    description: Whether to include Patches in the fetched versions. (WordPress is NOT compatible with this)
    default: "false"    
    
outputs:
  versions:
    description: The versions array in the format ["7.4","7.5","7.6"]

runs:
  using: node16
  main: get-plugin-releases.mjs
