name: Get release notes
description: Get release notes via GitHub, infer the next version and tag.

inputs:
  repo-token:
    description: The GITHUB_TOKEN secret.
    required: true

  package-dir:
    description: >
      The directory path of package.json. This action uses the version in package.json
      to generate a version tag name with the input tag-template, and check whether that
      tag exists to be used as the previous tag. The previous tag is the starting point of
      a range for getting the release notes.
    default: ""

  tag-template:
    description: >
      The template to generate a tag name with a version.
      For example, with a version 1.4.7,
      "v{version}" gets 'v1.4.7' and "my-tool-v{version}" gets 'my-tool-v1.4.7'.
    default: "{version}"

  tag:
    description: The tag name for the release. This can be an existing tag or leave it empty by default.
    default: ""

  target-commitish:
    description: >
      Specifies the commitish value that will be the target for the release's tag.
      If the input tag does not reference an existing tag, the default empty value
      will be replaced with the branch that triggers this action. If the input tag
      already exists, leave it empty by default.
    default: ""

  config-path:
    description: >
      Specifies a path to a file in the repository containing the config used for
      generating the release notes. If unspecified, the config file located in the
      repository at '.github/release.yml' will be used. If that is not present,
      the default config of GitHub will be used.
    default: ""

  major-keywords:
    description: Comma-separated keywords for matching the major level. For example, "breaking, major changes".
    default: "breaking"

  minor-keywords:
    description: Comma-separated keywords for matching the minor level. For example, "new features, improvements".
    default: "feature, enhancement"

outputs:
  release-notes:
    description: The content of release notes.

  release-notes-shell:
    description: The escaped "release-notes" for use in the shell.

  release-changelog:
    description: The changelog part in release notes.

  release-changelog-shell:
    description: The escaped "release-changelog" for use in the shell.

  next-version:
    description: The next version inferred via the release notes. For example, 2.0.0, 1.5.0 or 1.4.8.

  next-tag:
    description: The next tag name inferred via the release notes. For example, 2.0.0, v1.5.0 or my-tool-v1.4.8.

runs:
  using: node16
  main: get-release-notes.mjs
