name: Publish extension development build
description: Publish or update the extension development build via a pre-release on GitHub

inputs:    
  extension-asset-path:
    description: The extension asset path to find the existing asset for replacement or to upload. It will use the filename to match assets in the target release when finding.
    required: true

  extension-asset-content-type:
    description: The "Content-Type" HTTP header field indicates the media type of the extension asset.
    default: "application/zip"

  tag-name:
    description: The tag name to find the existing release for replacement or to create a release.
    default: "gha-dev-build"

  release-title:
    description: The release title.
    default: "Latest development build"

runs:
  using: composite
  steps:
    # Get unreleased notes
    - id: unreleased-notes
      uses: woocommerce/grow/get-release-notes@actions-v2
      with:
        repo-token: ${{ github.token }}
        tag-template: "{version}"

    # Publish the build to GitHub
    - uses: actions/github-script@v7
      with:
        # The main action inputs are not accessible within the "script" input of actions/github-script.
        # So it needs to do forwarding.
        script: |
          const actionPath = '${{ github.action_path }}';
          const { default: script } = await import( `${ actionPath }/publish-extension-dev-build.mjs` );

          const { 'release-changelog': changelog } = ${{ toJSON( steps.unreleased-notes.outputs ) }};
          const inputs = ${{ toJSON( inputs ) }};

          if ( ! inputs[ 'extension-asset-path' ] ) {
            core.setFailed( 'Input required and not supplied: extension-asset-path' );
            return;
          }

          inputs[ 'extension-asset-content-type' ] ??= 'application/zip';
          inputs[ 'tag-name' ] ??= 'gha-dev-build';
          inputs[ 'release-title' ] ??= 'Latest development build';

          await script( {
            github,
            context,
            core,
            changelog,
            inputs,
          } );
