name: PHPCS Diff
description: Run PHPCS to the changed lines of code, set error annotations to a pull request.

inputs:
  php-version:
    description: Specify PHP version. "7.4" by default.
    required: false
    default: "7.4"

runs:
  using: composite
  steps:
    # Checkout repository.
    - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      with:
        fetch-depth: 2

    # Set up PHP.
    - uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2
      with:
        php-version: ${{ inputs.php-version }}
        coverage: none

    # Log PHP and Composer information.
    - shell: bash
      run: |
        php --version
        composer --version

    # Cache Composer packages.
    - shell: bash
      id: composer-cache-config
      run: echo "dir=$(composer config cache-files-dir)" >> "$GITHUB_OUTPUT"

    - uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5
      with:
        path: ${{ steps.composer-cache-config.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-

    # Install Composer dependencies.
    - shell: bash
      run: |
        COMPOSER_VER=$(composer --version | awk '{ print $3 }')
        composer install --prefer-dist --no-interaction `if [[ $COMPOSER_VER == 1.* ]]; then printf %s "--no-suggest"; fi`
        echo "${PWD}/vendor/bin" >> "$GITHUB_PATH"

    #Log information
    - shell: bash
      run: |
        vendor/bin/phpcs -i
        vendor/bin/diffFilter -v

    # Run PHPCS with diffFilter in the coverageChecker.
    - shell: bash
      # When creating a pull request on GitHub, it will create a merge commit locally based on
      # the `head` and `base` branches of the PR. It's the same in GitHub Actions, when triggering
      # a workflow to a pull request, it uses the revision of a merge commit to run the workflow
      # as well. Therefore, `git diff HEAD^...HEAD` includes all diffs of a PR.
      run: |
        JSON_REPORT="/tmp/phpcs-diff.json"
        vendor/bin/diffFilter --phpcsStrict <(git diff HEAD^...HEAD) <(vendor/bin/phpcs ./* -q --report=json) --report=phpcs 0 > "$JSON_REPORT"

        # It's a workaround that prevents the empty result from being passed as a JSON file to annotate-phpcs-report.js
        # Related issue: https://github.com/exussum12/coverageChecker/issues/72
        if [ ! -s "$JSON_REPORT" ]; then
          echo "No changes."
          exit 0
        fi

        cd "${{ github.action_path }}"
        node annotate-phpcs-report.mjs "$JSON_REPORT"
        cd -

        TOTAL_ERRORS=$(jq ".totals.errors" "$JSON_REPORT")
        if [ "$TOTAL_ERRORS" != "0" ]; then
          exit 1
        fi
