name: Branch Type to Label
description: Set PR labels according to the branch name.

runs:
  using: composite
  steps:
    # Copy labeler.yml to the default config path of `actions/labeler`.
    - shell: bash
      run: |
        CONFIG_DIR=.github
        mkdir -p "$CONFIG_DIR"
        cp "${{ github.action_path }}/labeler.yml" "$CONFIG_DIR"

    - uses: actions/labeler@v5
