name: Get Plugin L-X release versions
description: Get release versions for the L-x releases from a specific Wordpress plugin like WooCommerce or Google Listing And Ads.

inputs:
  slug:
    description: The plugin slug (for WordPress.org) or the repository "owner/repo" (for GitHub) to get the versions.
    required: true
  source:
    description: The source of the releases. Options are "wordpress.org" or "github".
    default: "wordpress.org"
  github-token:
    description: The GitHub token for authentication. Required if the source is a private GitHub repository.
    default: ${{ github.token }}
  releases:
    description: Number of releases to get. By default L-2 directive (3 releases)
    default: "3"
  includeRC:
    description: Whether to include Release Candidates in the fetched versions. (WordPress is Not compatible with this)
    default: "false"
  includePatches:
    description: Whether to include Patches in the fetched versions. (WordPress is NOT compatible with this)
    default: "false"    
    
outputs:
  versions:
    description: The versions array in the format ["7.4","7.5","7.6"]

runs:
  using: node24
  main: get-plugin-releases.mjs
