name: Auto merge a released trunk
description: Automatically merge trunk to develop after a release.

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: "Merge the release to develop"
      shell: bash
      if: ${{ github.event.pull_request.merged == true && startsWith(github.head_ref, 'release/') && github.event.pull_request.user.login == 'github-actions[bot]' }}
      # Use the github-actions bot account to commit.
      # https://api.github.com/users/github-actions%5Bbot%5D
      run: |
        git config user.name github-actions[bot]
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
        git fetch origin develop trunk --unshallow --no-tags
        git checkout develop
        git merge --no-ff origin/trunk -m "Automerge ${{ github.head_ref }} from trunk to develop"
        git push
