name: Stylelint annotattion formatter
description: Annotate stylelint results via stylelint formatter.

inputs:
  formatter-dest:
    description: The relative path to place the stylelint formatter script. Please use a destination file path within the caller repository since the script will depends on the stylelint package installed in it.
    default: "./stylelintFormatter.cjs"

runs:
  using: composite
  steps:
    # Copy formatter script to the destination file path.
    - shell: bash
      run: |
        SCRIPT_DEST="${{ inputs.formatter-dest }}"
        mkdir -p $(dirname "$SCRIPT_DEST")
        echo '/* eslint-disable */' > "$SCRIPT_DEST"
        cat "${{ github.action_path }}/stylelintFormatter.cjs" >> "$SCRIPT_DEST"
