name: GitHub Actions - Create Release

on:
  pull_request_review:
    types:
      - submitted

jobs:
  CreateRelease:
    name: Create release for github-actions package
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.head.ref == 'release/actions' && github.event.review.state == 'approved' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

      - name: Create release
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9
        with:
          script: |
            const workspace = '${{ github.workspace }}';
            const { default: script } = await import( `${ workspace }/.github/scripts/create-release.mjs` );
            await script( {
              github,
              context,
              outputJsonPath: '/tmp/release.json',
              packageDir: 'packages/github-actions',
              packageName: 'github-actions',
              tagPrefix: 'actions-v',
            } );

      - name: Upload release artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: release
          path: /tmp/release.json
