name: PHP Coding Standards

on:
  push:
    branches:
      - "trunk"
    paths:
      - "**.php"
      - composer.json
      - composer.lock
      - "**/composer.json"
      - "**/composer.lock"
      - phpcs.xml.dist
      - .github/workflows/php-coding-standards.yml
  pull_request:
    paths:
      - "**.php"
      - composer.json
      - composer.lock
      - "**/composer.json"
      - "**/composer.lock"
      - phpcs.xml.dist
      - .github/workflows/php-coding-standards.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  phpcs:
    name: PHP coding standards
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

      - name: Prepare PHP
        uses: ./packages/github-actions/actions/prepare-php
        with:
          php-version: 7.4
          tools: cs2pr
          install-deps: "no"

      - name: Install Composer dependencies
        run: |
          # Skip installing packages from private repos.
          composer remove --dev woocommerce/woorelease
          composer install --prefer-dist --no-interaction

      - name: Log PHPCS information
        run: vendor/bin/phpcs -i

      - name: Run PHPCS on all files
        run: vendor/bin/phpcs -q --report=checkstyle | cs2pr
